#!/bin/bash

echo donner le lien du site a set-inform \n
read $inform
echo $inform

#--------------------------------partie reset des fichiers-------------------------------------------

echo partie reset \n
echo >./file
echo >./file2
touch file2.temp
echo >./file3
#--------------------------------partie récupération des données-------------------------------------
echo partie récup \n
ssh admin@192.168.16.1 << 'eof' > ./file
ip dhcp-server lease print
eof
cat file | awk '{print $3 "      " $4 "     " "test"}' | sed 1d | sed 1d >> ./file2

#--------------------------------partie vérification addresse IP-------------------------------------
echo partie IP \n
cat file | awk '{print $4 "      " $5"     " "test"}' | sed 1d | sed 1d > ./file2.temp
num_ip=`cat file2.temp | wc -l`
compteur_ip=0
var_ip=1
while [ "$(echo $compteur_ip)" != "$(echo $num_ip)" ]
        do
        ip_pc=`cat file2.temp | awk '{print $1}' | sed 's/\./ /g' | awk '{print $1$2$3}' |head -n$var_ip | tail -n1`
        ip_fixe=19216816

        if [ "$ip_pc" == "$ip_fixe" ]
        then
                echo $ip_pc non transféré
		let var_ip++
        fi

        if [ "$ip_pc" != "$ip_fixe" ]
        then
                echo $ip_pc transféré
               cat file2.temp | awk '{print $1"       "$2"       "$3}' |head -n$var | tail -n1 > ./file2
               fi
        let compteur_ip++
done

#--------------------------------partie vérification addresse mac-------------------------------------
echo partie mac \n
ligne_fichier3=`cat ./file3 | wc -l`
ligne_fichier2=`cat ./file2 | wc -l`
compteur1_mac=0
var1_mac=1
while [ "$(echo $ligne_fichier2)" != "$compteur1_mac" ]
	do
	var2_mac=1
	mac_a=`cat ./file2 | grep -oE '([[:xdigit:]]{1,2}:){5}[[:xdigit:]]{1,2}' | head -n$var1_mac | tail -n1 |sed 's/://g'`
	compteur_mac=0
	var3_mac=2
	while [ "$(echo $compteur_mac)" != "$(echo $ligne_fichier3)" ]
	do
		mac_b=`cat ./file3 | grep -oE '([[:xdigit:]]{1,2}:){5}[[:xdigit:]]{1,2}' | head -n$var2_mac | tail -n1 |sed 's/://g'`
		if [ "$(echo $mac_a)" ==  "$(echo $mac_b)" ]
		then
			let var3_mac=1
			let var1_mac++
			break
		fi
	
		if [ "$(echo $mac_a)" != "$(echo $mac_b)" ]
		then
			let var2_mac++
		fi
		let compteur_mac++
	done

	if [ "$(echo $var3_mac)" == "2" ]       	
	then
		transfert=`cat ./file2 | head -n$var1_mac | tail -n1`
        	echo $transfert >> file3
		let var1_mac++
	fi
	
	let compteur1_mac++
done

#--------------------------------partie set-inform--------------------------------------------
echo partie set-inform \n
var_inform=0
var1_inform=1
IP=`cat ./file3 |  awk '{print $1}' | head -n$var1_inform | tail -n1  `
while [ "$var_inform" != "$ligne_fichier3" ]
do

ssh-keygen -f "/root/.ssh/known_hosts" -R "$IP"
ssh ubnt@$IP << 'eof'
set-inform $inform
eof

let var1_inform++
let var_inform++
let IP++

done
