#!/bin/bash

echo -e "donner le lien du site a set-inform \n"
read inform
echo $inform sera donc le lien utilisé dans le set-inform

#--------------------------------partie reset des fichiers-------------------------------------------

echo -e "\npartie reset \n"

echo -e "\n">file
echo -e "\n">file2
echo -e "\n">file2.temp

#--------------------------------partie récupération des données-------------------------------------

echo -e "\npartie récup \n"

ssh admin@192.168.16.1 << 'eof' > ./file
ip dhcp-server lease print
eof
cat file | awk '{print $3 "      " $4}' |sed 1d |sed 1d > ./file2.temp
echo -e "contenue du fhichier temporaire :\n`cat file2.temp`"

#--------------------------------partie vérification addresse IP-------------------------------------

echo -e "\npartie IP \n"

num_ip=`cat file2.temp | wc -l`
compteur_ip=0
var_ip=1
while [ "$(echo $compteur_ip)" != "$(echo $num_ip)" ]
        do
        ip_pc=`cat file2.temp | awk '{print $1}' | sed 's/\./ /g' | awk '{print $1$2$3}' |head -n$var_ip | tail -n1`
        ip_fixe=19216816

        if [ "$ip_pc" == "$ip_fixe" ]
        then
                
		echo -e "`cat file2.temp | awk '{print $2}' |head -n$var_ip | tail -n1` non transféré\n"
		let var_ip++
        fi

        if [ "$ip_pc" != "$ip_fixe" ]
        then
                
		echo -e "`cat file2.temp | awk '{print $2}' |head -n$var_ip | tail -n1` transféré\n"
		cat file2.temp | awk '{print $1"       "$2}' |head -n$var_ip | tail -n1 >> ./file2
	        let var_ip++
        fi
        let compteur_ip++
done

suppression_du_vide2=`grep "\s" file2`
echo $suppression_du_vide2
echo $suppression_du_vide2 > file2

#--------------------------------partie vérification addresse mac-------------------------------------

echo -e "\npartie mac \n"

ligne_fichier3=`cat ./file3 | wc -l`
ligne_fichier2=`cat ./file2 | wc -l`
compteur1_mac=0
var1_mac=1
while [ "$(echo $ligne_fichier2)" != "$compteur1_mac" ]
	do
	var2_mac=1
	mac_a=`cat ./file2 | grep -oE '([[:xdigit:]]{1,2}:){5}[[:xdigit:]]{1,2}' | head -n$var1_mac | tail -n1 |sed 's/://g'`
	compteur_mac=0
	var3_mac=2
	while [ "$(echo $compteur_mac)" != "$(echo $ligne_fichier3)" ]
	do
		mac_b=`cat ./file3 | grep -oE '([[:xdigit:]]{1,2}:){5}[[:xdigit:]]{1,2}' | head -n$var2_mac | tail -n1 |sed 's/://g'`
		if [ "$(echo $mac_a)" ==  "$(echo $mac_b)" ]
		then
			let var3_mac=1
			let var1_mac++
			break
		fi
	
		if [ "$(echo $mac_a)" != "$(echo $mac_b)" ]
		then
			let var2_mac++
		fi
		let compteur_mac++
	done

	if [ "$(echo $var3_mac)" == "2" ]       	
	then
		transfert=`cat ./file2 | head -n$var1_mac | tail -n1`
        	echo $transfert >> file3
		let var1_mac++
	fi
 
	while [ "$(echo $ligne_fichier3)" == "0" ]	
	do
		transfert=`cat ./file2 | sed 1d | head -n$var1_mac | tail -n1`
                echo $transfert >> file3
                let var1_mac++

	done
	let compteur1_mac++
done
echo -e "\n contenur du fichier a inform `cat ./file3`\n"

suppression_du_vide3=`grep "\s" file3`
echo $suppression_du_vide3
echo $suppression_du_vide3 > file3

#--------------------------------partie set-inform--------------------------------------------

echo -e "\npartie set-inform \n"


var_inform=0
var1_inform=1
IP=`cat ./file3 | awk '{print $1}' | head -n$var1_inform | tail -n1`
echo $IP


while [ "$var_inform" != "$ligne_fichier3" ]
do
echo -e "\n ssh de $IP sur le controlleur $inform\n"
ssh-keygen -f "/root/.ssh/known_hosts" -R "$IP"
ssh ubnt@$IP << eof
set-inform $inform
eof

let var1_inform++
let var_inform++

done
